### ISSUE TITLE
Send Command

### ISSUE THREAD

**Issue by srbalan** [Arti3DPlayer/USBDeviceSwift#12]
Hi there,

First of all, I would like to thank you for your effort to create this library. This is absolutely helpful!

I just want to ask for your support as I don't have idea how to send this command to a USB device:

Reboot command: 0xdf 0x40

I need your help on this. Thanks so much!

**Comment by Arti3DPlayer** [comment]
Look on stm32 example:

https://github.com/Arti3DPlayer/USBDeviceSwift/blob/master/STM32DeviceExample/STM32DeviceExample/STM32Device.swift#L14

just send this value `0xdf`

**Comment by srbalan** [comment]
Could you check if this is correct? Attached are the screenshots of the code and the result. The USB device didn't reboot :(

![Screen Shot 2019-05-07 at 3 57 17 pm](https://user-images.githubusercontent.com/18670195/57283149-1132b880-70e1-11e9-9fb3-656b8888c1f2.png)
<img width="523" alt="Screen Shot 2019-05-07 at 3 58 02 pm" src="https://user-images.githubusercontent.com/18670195/57283163-16900300-70e1-11e9-8413-bb1b8de6069b.png">

**Comment by Arti3DPlayer** [comment]
@srbalan You should find a USB device manual and check what this response means

**Comment by srbalan** [comment]
Thanks so much for your prompt response.

I am just wandering what happened to the 0x40 since the reboot command is
