### ISSUE TITLE
HID support missing in Cocoa Pod

### ISSUE THREAD

**Issue by gnichs** [Arti3DPlayer/USBDeviceSwift#2]
Hi @Arti3DPlayer,

It seems that support for HID device communication isn't included in the Cocoa Pods USBDeviceSwift package. Looking in my Pods folder, I can see the USBDevice struct and the USBDeviceMonitor class, but I don't see the HIDDevice struct or HIDDeviceMonitor class or the others referenced in your examples and documentation. When trying to follow the HID example from your documentation, I receive unresolved identifier errors.

![screen shot 2017-08-03 at 10 17 42 am](https://user-images.githubusercontent.com/3280485/28926186-09767448-7835-11e7-8cee-06fda34a358f.png)

**Comment by gnichs** [comment]
Solved by changing Podfile reference from

```
'USBDeviceSwift'
```
to
```
'USBDeviceSwift', '~>1.0.0'
```

**Comment by Arti3DPlayer** [comment]
@gnichs thnaks, i will update master
