### ISSUE TITLE
Pod is detected as Swift 2.x and is unsupported in Xcode 9

### ISSUE THREAD

**Issue by Dids** [Arti3DPlayer/USBDeviceSwift#3]
```
The target “USBDeviceSwift” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.
```

Has the pod just not been updated?

**Comment by Dids** [comment]
Also seeing this when trying to include USBDeviceSwift and build:

```
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

It should be noted that I'm using Objective-C and Swift.

**Comment by Arti3DPlayer** [comment]
@Dids Weird, it should be on swift 3. I will look, but try to set `pod 'USBDeviceSwift' ~> '1.0.1'`

**Comment by Dids** [comment]
I did and it's definitely on 1.0.1, but could be a compatibility quirk with either Xcode or bridging header/compatibility between the two languages.

Just checked and this library's target is definitely set to Swift 3.2, although the project's Swift version is "unspecified". I'll try to tinker with the source too, see if I can get it to behave. :)

**Comment by Arti3DPlayer** [comment]
@Dids thanks! did you figure out issue with obj-c ?

**Comment by Dids** [comment]
@Arti3DPlayer Well, including the library builds just fine, I'm just trying to figure out the correct methods for calling the library from Objective-C now. Everything apart from `USBDeviceMonitor` initialization seems to have been easy to figure out, but still stuck on figuring that one out, although I'm sure I'll figure it out at some point. :)

**Comment by Dids** [comment]
Alternatively I'll just learn Swift instead, so it's no biggie, hehe.

**Comment by Arti3DPlayer** [comment]
@Dids I have pushed your changes to cocoapods.
 🎉  Congrats

 🚀  USBDeviceSwift (1.0.2) successfully published
 📅  October 21st, 14:16
 🌎  https://cocoapods.org/pods/USBDeviceSwift
 👍  Tell your friends!
