### ISSUE TITLE
Porting PyUSB logic to USBDeviceSwift

### ISSUE THREAD

**Issue by Dids** [Arti3DPlayer/USBDeviceSwift#5]
_This is more of a request for help than an actual issue, but I feel like I'm fairly lost at this point._

I'm essentially trying to figure out how to port something like [this](https://github.com/jaksi/leviathan/blob/master/PROTOCOL.md), to USBDeviceSwift/IOKit.

As you can see from the protocol link above, the requests are fairly straightforward to construct (apart from wLenDone, which I'm still confused about), but the main issue I have is how I'd handle the way PyUSB provides a `write` function, as the first parameter is always referred to as an `endpoint`, which does not sound like a request type etc.

To make things more confusing, I don't actually have a Kraken X61, but an X62, which has an entirely different protocol. That said, I'm trying to at least replicate the logic [here](https://github.com/leaty/camctl/blob/master/camctl), which is specifically for the X62, but notice how there is no request logic there at all, only `write` calls, so I'm stumped trying to find a way to write byte data to a specific "endpoint", using USBDeviceSwift.

Every bit of information to help me along would be massively appreciated!

**Comment by Arti3DPlayer** [comment]
@Dids ok, I recommend for you to take a look on `STM32DeviceExample`. Did you see my example?

https://github.com/Arti3DPlayer/USBDeviceSwift#send-command-to-usb-device-example

**Comment by Arti3DPlayer** [comment]
As I see in doc: https://github.com/jaksi/leviathan/blob/master/PROTOCOL.md#initialization, first request will be like this:
```
 var request = IOUSBDevRequest(bmRequestType: 0x40,
                                  bRequest: 2,
                                  wValue: 0x0002,
                                  wIndex: 0,
                                  wLength: 0,
                                  pData: &requestPtr,
                                  wLenDone: 255)
```

So in `requestPtr` your will receive answer from your board, and it shoud return:

```kr = deviceInterface.DeviceRequest(self.deviceInfo.deviceInterfacePtrPtr, &request)```

success here

**Comment by Arti3DPlayer** [comment]
You also colud use STM32DeviceExample to check responses. Just change vid & pid. and test messages  by modifying send function

**Comment by Dids** [comment]
@Arti3DPlayer Yes, I did, and that did indeed help me with the request logic for the protocol mentioned in the first link, which unfortunately I can't confirm if it's working or not, since the protocol ended up being different (X61 vs X62). The USB device request with IOKit/USBDeviceSwift are fairly straightforward, especially with the examples you've provided.

However, since the second link's code doesn't seem to specify (or even use) a protocol or request at all, but instead simply writes raw data to the USB device, I'm not quite sure how I'd accomplish that with IOKit, which is where I'm currently stuck.

**Comment by Dids** [comment]
Just to reiterate, I don't have any issues with how the requests work in regards to the example project, but more with the equivalent logic of PyUSB's `write` calls, which seem to work without specifying any requests or request parameters at all.

**Comment by Dids** [comment]
Ah, looks like PyUSB's `write` function was just confusing me: https://github.com/walac/pyusb/blob/7a1ce1eb5bd6f80849f11da566ba1e484c200bbe/usb/core.py#L376

It's essentially just a wrapper for USB requests, but it's automatically figuring out the request type and parameters, which I didn't realize before, thinking that there was a universal/standard way of writing raw data to USB device. Guess I'll just need to replicate their logic for figuring out the parameters and go from there.

**Comment by Arti3DPlayer** [comment]
@Dids Yes it is standard. So they should have all this fields.

**Comment by Arti3DPlayer** [comment]
https://github.com/walac/pyusb/blob/7a1ce1eb5bd6f80849f11da566ba1e484c200bbe/usb/core.py#L941

**Comment by Arti3DPlayer** [comment]
@Dids take a look on constants: https://github.com/walac/pyusb/blob/7a1ce1eb5bd6f80849f11da566ba1e484c200bbe/usb/util.py

**Comment by Arti3DPlayer** [comment]
@Dids I would better find documentation about device or find something on c#, c that will have strict typing. Or debug via print this python functions:)

**Comment by Dids** [comment]
Unfortunately libusb doesn't play nice with C# on macOS, so I'm going the native/cocoa route.

In any case, I'm pretty confident I can figure it out with this information, so thank you very, very much for pointing me in the right direction, as well as clearing things up regarding the request standards etc. :)

**Comment by tonyarnold** [comment]
@Dids did you make any further progress with this? I've managed to get a Kraken X62 reporting status by using `HIDDevice`, but I cannot read/write any data to the device.

**Comment by Dids** [comment]
I ended up writing my own low level USB library/wrapper in Objective-C, then created a binding library to be able to use that with C#, which eventually lead to a full blown desktop macOS app that currently supports most NZXT peripherals.

**Comment by Dids** [comment]
Unfortunately no, not at the moment. Not sure yet if I'll release the source, or just the binaries. It's a bit of a grey area, so I'll eventually have to ask how NZXT feels about it, then decide what to do with the project. It took me a good 6 months to get it working.

**Comment by tonyarnold** [comment]
Completely understandable! Good luck with it 👍🏻
