### ISSUE TITLE
How to make same request as with PyUSB write method

### ISSUE THREAD

**Issue by kolpav** [Arti3DPlayer/USBDeviceSwift#7]
Hello,

Can you please help me make same request using `IOUSBDevRequest` as if I was using PyUSB `write` function? I don't know if you are familiar with PyUSB but It has very simple api just `dev.write('hello')` and automatically calculates `bmRequestType`, `bmRequest` do you think this library could have same api or can you tell me how should I go about setting `bmRequestType` and `bmRequest`?

I know very little about USB so I don't know if it is even possible

**Comment by kolpav** [comment]
Sorry I missed that issue because it is exactly what I am trying to achieve I played with STM32DeviceExample and also read through PyUSB code but I am still unable to replicate the `write` behaviour as I am new to swift and python.

This is modified example I am working with
```
enum STM32REQUEST_TYPE_DIRECTION:UInt8 {
    case USB_SETUP_HOST_TO_DEVICE = 0x00
    case USB_SETUP_DEVICE_TO_HOST = 0x80     
}
enum STM32REQUEST_TYPE_TYPE:UInt8 {
    case USB_SETUP_TYPE_STANDARD = 0x00      
    case USB_SETUP_TYPE_CLASS = 0x20        
    case USB_SETUP_TYPE_VENDOR = 0x40         
}
enum STM32REQUEST_TYPE_RECIPIENT:UInt8 {
    case USB_SETUP_RECIPIENT_DEVICE = 0x00    
    case USB_SETUP_RECIPIENT_INTERFACE = 0x01 
    case USB_SETUP_RECIPIENT_ENDPOINT = 0x02 
    case USB_SETUP_RECIPIENT_OTHER = 0x03     
}
        var kr:Int32 = 0
        var requestPtr:[UInt8] = [1, 2, 3];
        let bmRequest = STM32REQUEST.GETSTATUS.rawValue;
        let bmRequestType:UInt8 =
            STM32REQUEST_TYPE_DIRECTION.USB_SETUP_HOST_TO_DEVICE.rawValue |
            STM32REQUEST_TYPE_TYPE.USB_SETUP_TYPE_VENDOR.rawValue |
            STM32REQUEST_TYPE_RECIPIENT.USB_SETUP_RECIPIENT_DEVICE.rawValue;
        // Creating request
        var request = IOUSBDevRequest(bmRequestType: bmRequestType,
                                      bRequest: bmRequest,
                                      wValue: 0,
                                      wIndex: 0,
                                      wLength: UInt16(requestPtr.count),
                                      pData: &requestPtr,
                                      wLenDone: 255)
```
You were able to calculate bmRequestType value in your head
[here](https://github.com/Arti3DPlayer/USBDeviceSwift/blob/4f9ce757a1ac6c479c3114e6043d5d4d65458c29/STM32DeviceExample/STM32DeviceExample/STM32Device.swift#L46) you just typed 161 that suggests you understand how it works can you please tell me what I am doing wrong? Or how it is possible to automatically calculate `bmRequestType` and `bRequest`? I looked at how the PyUSB library is doing it but I still don't understand.

**Comment by Arti3DPlayer** [comment]
Oh, yes you are right. I didn't calculate it with function, that implement here:

https://github.com/Arti3DPlayer/USBDeviceSwift/blob/master/Sources/USBDevice.swift#L33

**Comment by Arti3DPlayer** [comment]
So you need to mix values based on what you want to do to get requestType
